INSERT INTO organisations (name) VALUES ('Organisation1');
INSERT INTO organisations (name) VALUES ('Organisation2');
INSERT INTO organisations (name) VALUES ('Organisation3');
INSERT INTO organisations (name) VALUES ('Organisation4');
INSERT INTO organisations (name) VALUES ('Organisation5');
INSERT INTO organisations (name) VALUES ('Organisation6');
INSERT INTO organisations (name) VALUES ('Organisation7');
INSERT INTO organisations (name) VALUES ('Organisation8');
INSERT INTO organisations (name) VALUES ('Organisation9');
INSERT INTO organisations (name) VALUES ('Organisation10');

INSERT INTO users (username, email, organisation_id) VALUES ('Jan Kowalski', 'Jan.Kowalski@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation1'));
INSERT INTO users (username, email, organisation_id) VALUES ('Sebastian Kowalski', 'Sebastian.Kowalski@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation1'));
INSERT INTO users (username, email, organisation_id) VALUES ('Wojciech Kowalski', 'Wojciach.Kowalski@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation1'));
INSERT INTO users (username, email, organisation_id) VALUES ('Daniel Kowalski', 'daniel.kowalski@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation1'));
INSERT INTO users (username, email, organisation_id) VALUES ('Piotr Kowalski', 'Piotr.Kowalski@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation1'));
INSERT INTO users (username, email, organisation_id) VALUES ('Eryk Kowalski', 'eryk.kowalski@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation1'));
INSERT INTO users (username, email, organisation_id) VALUES ('Krzysztof Kowalski', 'Krzysztof.Kowalski@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation1'));
INSERT INTO users (username, email, organisation_id) VALUES ('Cecylia Kowalski', 'cecylia.kowalski@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation1'));
INSERT INTO users (username, email, organisation_id) VALUES ('Barbara Kowalski', 'barbara.kowalski@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation1'));
INSERT INTO users (username, email, organisation_id) VALUES ('Adam Kowalski', 'adam.kowalski@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation1'));

INSERT INTO users (username, email, organisation_id) VALUES ('Jan Nowak', 'Jan.Nowak@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation2'));
INSERT INTO users (username, email, organisation_id) VALUES ('Sebastian Nowak', 'Sebastian.Nowak@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation2'));
INSERT INTO users (username, email, organisation_id) VALUES ('Wojciech Nowak', 'Wojciach.Nowak@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation2'));
INSERT INTO users (username, email, organisation_id) VALUES ('Paweł Nowak', 'Paweł.Nowak@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation2'));
INSERT INTO users (username, email, organisation_id) VALUES ('Piotr Nowak', 'Piotr.Nowak@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation2'));
INSERT INTO users (username, email, organisation_id) VALUES ('Jacek Nowak', 'Jacek.Nowak@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation2'));
INSERT INTO users (username, email, organisation_id) VALUES ('Krzysztof Nowak', 'Krzysztof.Nowak@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation2'));
INSERT INTO users (username, email, organisation_id) VALUES ('Michał Nowak', 'Michał.Nowak@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation2'));
INSERT INTO users (username, email, organisation_id) VALUES ('Bogdan Nowak', 'Bogdan.Nowak@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation2'));
INSERT INTO users (username, email, organisation_id) VALUES ('Adam Nowak', 'Adam.Nowak@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation2'));

INSERT INTO users (username, email, organisation_id) VALUES ('Jan Gos', 'Jan.Gos@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation3'));
INSERT INTO users (username, email, organisation_id) VALUES ('Sebastian Gos', 'Sebastian.Gos@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation3'));
INSERT INTO users (username, email, organisation_id) VALUES ('Wojciech Gos', 'Wojciach.Gos@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation3'));
INSERT INTO users (username, email, organisation_id) VALUES ('Paweł Gos', 'Paweł.Gos@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation3'));
INSERT INTO users (username, email, organisation_id) VALUES ('Piotr Gos', 'Piotr.Gos@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation3'));
INSERT INTO users (username, email, organisation_id) VALUES ('Jacek Gos', 'Jacek.Gos@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation3'));
INSERT INTO users (username, email, organisation_id) VALUES ('Krzysztof Gos', 'Krzysztof.Gos@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation3'));
INSERT INTO users (username, email, organisation_id) VALUES ('Michał Gos', 'Michał.Gos@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation3'));
INSERT INTO users (username, email, organisation_id) VALUES ('Bogdan Gos', 'Bogdan.Gos@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation3'));
INSERT INTO users (username, email, organisation_id) VALUES ('Adam Gos', 'Adam.Gos@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation3'));

INSERT INTO users (username, email, organisation_id) VALUES ('Jan Duda', 'Jan.Duda@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation4'));
INSERT INTO users (username, email, organisation_id) VALUES ('Sebastian Duda', 'Sebastian.Duda@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation4'));
INSERT INTO users (username, email, organisation_id) VALUES ('Wojciech Duda', 'Wojciach.Duda@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation4'));
INSERT INTO users (username, email, organisation_id) VALUES ('Paweł Duda', 'Paweł.Duda@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation4'));
INSERT INTO users (username, email, organisation_id) VALUES ('Piotr Duda', 'Piotr.Duda@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation4'));
INSERT INTO users (username, email, organisation_id) VALUES ('Jacek Duda', 'Jacek.Duda@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation4'));
INSERT INTO users (username, email, organisation_id) VALUES ('Krzysztof Duda', 'Krzysztof.Duda@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation4'));
INSERT INTO users (username, email, organisation_id) VALUES ('Michał Duda', 'Michał.Duda@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation4'));
INSERT INTO users (username, email, organisation_id) VALUES ('Bogdan Duda', 'Bogdan.Duda@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation4'));
INSERT INTO users (username, email, organisation_id) VALUES ('Adam Duda', 'Adam.Duda@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation4'));

INSERT INTO users (username, email, organisation_id) VALUES ('Jan Morawiecki', 'Jan.Morawiecki@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation5'));
INSERT INTO users (username, email, organisation_id) VALUES ('Sebastian Morawiecki', 'Sebastian.Morawiecki@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation5'));
INSERT INTO users (username, email, organisation_id) VALUES ('Wojciech Morawiecki', 'Wojciach.Morawiecki@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation5'));
INSERT INTO users (username, email, organisation_id) VALUES ('Paweł Morawiecki', 'Paweł.Morawiecki@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation5'));
INSERT INTO users (username, email, organisation_id) VALUES ('Piotr Morawiecki', 'Piotr.Morawiecki@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation5'));
INSERT INTO users (username, email, organisation_id) VALUES ('Jacek Morawiecki', 'Jacek.Morawiecki@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation5'));
INSERT INTO users (username, email, organisation_id) VALUES ('Krzysztof Morawiecki', 'Krzysztof.Morawiecki@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation5'));
INSERT INTO users (username, email, organisation_id) VALUES ('Michał Morawiecki', 'Michał.Morawiecki@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation5'));
INSERT INTO users (username, email, organisation_id) VALUES ('Bogdan Morawiecki', 'Bogdan.Morawiecki@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation5'));
INSERT INTO users (username, email, organisation_id) VALUES ('Adam Morawiecki', 'Adam.Morawiecki@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation5'));

INSERT INTO users (username, email, organisation_id) VALUES ('Jan Macierewicz', 'Jan.Macierewicz@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation6'));
INSERT INTO users (username, email, organisation_id) VALUES ('Sebastian Macierewicz', 'Sebastian.Macierewicz@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation6'));
INSERT INTO users (username, email, organisation_id) VALUES ('Wojciech Macierewicz', 'Wojciach.Macierewicz@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation6'));
INSERT INTO users (username, email, organisation_id) VALUES ('Paweł Macierewicz', 'Paweł.Macierewicz@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation6'));
INSERT INTO users (username, email, organisation_id) VALUES ('Piotr Macierewicz', 'Piotr.Macierewicz@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation6'));
INSERT INTO users (username, email, organisation_id) VALUES ('Jacek Macierewicz', 'Jacek.Macierewicz@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation6'));
INSERT INTO users (username, email, organisation_id) VALUES ('Krzysztof Macierewicz', 'Krzysztof.Macierewicz@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation6'));
INSERT INTO users (username, email, organisation_id) VALUES ('Michał Macierewicz', 'Michał.Macierewicz@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation6'));
INSERT INTO users (username, email, organisation_id) VALUES ('Bogdan Macierewicz', 'Bogdan.Macierewicz@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation6'));
INSERT INTO users (username, email, organisation_id) VALUES ('Adam Macierewicz', 'Adam.Macierewicz@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation6'));

INSERT INTO users (username, email, organisation_id) VALUES ('Jan Tusk', 'Jan.Tusk@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation7'));
INSERT INTO users (username, email, organisation_id) VALUES ('Sebastian Tusk', 'Sebastian.Tusk@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation7'));
INSERT INTO users (username, email, organisation_id) VALUES ('Wojciech Tusk', 'Wojciach.Tusk@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation7'));
INSERT INTO users (username, email, organisation_id) VALUES ('Paweł Tusk', 'Paweł.Tusk@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation7'));
INSERT INTO users (username, email, organisation_id) VALUES ('Piotr Tusk', 'Piotr.Tusk@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation7'));
INSERT INTO users (username, email, organisation_id) VALUES ('Jacek Tusk', 'Jacek.Tusk@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation7'));
INSERT INTO users (username, email, organisation_id) VALUES ('Krzysztof Tusk', 'Krzysztof.Tusk@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation7'));
INSERT INTO users (username, email, organisation_id) VALUES ('Michał Tusk', 'Michał.Tusk@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation7'));
INSERT INTO users (username, email, organisation_id) VALUES ('Bogdan Tusk', 'Bogdan.Tusk@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation7'));
INSERT INTO users (username, email, organisation_id) VALUES ('Adam Tusk', 'Adam.Tusk@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation7'));

INSERT INTO users (username, email, organisation_id) VALUES ('Jan Sikorski', 'Jan.Sikorski@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation8'));
INSERT INTO users (username, email, organisation_id) VALUES ('Sebastian Sikorski', 'Sebastian.Sikorski@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation8'));
INSERT INTO users (username, email, organisation_id) VALUES ('Wojciech Sikorski', 'Wojciach.Sikorski@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation8'));
INSERT INTO users (username, email, organisation_id) VALUES ('Paweł Sikorski', 'Paweł.Sikorski@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation8'));
INSERT INTO users (username, email, organisation_id) VALUES ('Piotr Sikorski', 'Piotr.Sikorski@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation8'));
INSERT INTO users (username, email, organisation_id) VALUES ('Jacek Sikorski', 'Jacek.Sikorski@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation8'));
INSERT INTO users (username, email, organisation_id) VALUES ('Krzysztof Sikorski', 'Krzysztof.Sikorski@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation8'));
INSERT INTO users (username, email, organisation_id) VALUES ('Michał Sikorski', 'Michał.Sikorski@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation8'));
INSERT INTO users (username, email, organisation_id) VALUES ('Bogdan Sikorski', 'Bogdan.Sikorski@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation8'));
INSERT INTO users (username, email, organisation_id) VALUES ('Adam Sikorski', 'Adam.Sikorski@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation8'));

INSERT INTO users (username, email, organisation_id) VALUES ('Jan Braun', 'Jan.Braun@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation9'));
INSERT INTO users (username, email, organisation_id) VALUES ('Sebastian Braun', 'Sebastian.Braun@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation9'));
INSERT INTO users (username, email, organisation_id) VALUES ('Wojciech Braun', 'Wojciach.Braun@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation9'));
INSERT INTO users (username, email, organisation_id) VALUES ('Paweł Braun', 'Paweł.Braun@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation9'));
INSERT INTO users (username, email, organisation_id) VALUES ('Piotr Braun', 'Piotr.Braun@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation9'));
INSERT INTO users (username, email, organisation_id) VALUES ('Jacek Braun', 'Jacek.Braun@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation9'));
INSERT INTO users (username, email, organisation_id) VALUES ('Krzysztof Braun', 'Krzysztof.Braun@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation9'));
INSERT INTO users (username, email, organisation_id) VALUES ('Michał Braun', 'Michał.Braun@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation9'));
INSERT INTO users (username, email, organisation_id) VALUES ('Bogdan Braun', 'Bogdan.Braun@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation9'));
INSERT INTO users (username, email, organisation_id) VALUES ('Adam Braun', 'Adam.Braun@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation9'));

INSERT INTO users (username, email, organisation_id) VALUES ('Jan Mikke', 'Jan.Mikke@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation10'));
INSERT INTO users (username, email, organisation_id) VALUES ('Sebastian Mikke', 'Sebastian.Mikke@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation10'));
INSERT INTO users (username, email, organisation_id) VALUES ('Wojciech Mikke', 'Wojciach.Mikke@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation10'));
INSERT INTO users (username, email, organisation_id) VALUES ('Paweł Mikke', 'Paweł.Mikke@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation10'));
INSERT INTO users (username, email, organisation_id) VALUES ('Piotr Mikke', 'Piotr.Mikke@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation10'));
INSERT INTO users (username, email, organisation_id) VALUES ('Jacek Mikke', 'Jacek.Mikke@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation10'));
INSERT INTO users (username, email, organisation_id) VALUES ('Krzysztof Mikke', 'Krzysztof.Mikke@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation10'));
INSERT INTO users (username, email, organisation_id) VALUES ('Michał Mikke', 'Michał.Mikke@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation10'));
INSERT INTO users (username, email, organisation_id) VALUES ('Bogdan Mikke', 'Bogdan.Mikke@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation10'));
INSERT INTO users (username, email, organisation_id) VALUES ('Adam Mikke', 'Adam.Mikke@gmail.com', (SELECT id FROM organisations WHERE name LIKE 'Organisation10'));

INSERT INTO roles (name) VALUES ('viewer');
INSERT INTO roles (name) VALUES ('guest');
INSERT INTO roles (name) VALUES ('observer');
INSERT INTO roles (name) VALUES ('visitor');
INSERT INTO roles (name) VALUES ('admin');
INSERT INTO roles (name) VALUES ('global admin');
INSERT INTO roles (name) VALUES ('custom');
INSERT INTO roles (name) VALUES ('reader');
INSERT INTO roles (name) VALUES ('editor');
INSERT INTO roles (name) VALUES ('default');

INSERT INTO role_permissions (role_id, permissions) VALUES ((SELECT id FROM roles WHERE name LIKE 'viewer'), 'USER_READ');
INSERT INTO role_permissions (role_id, permissions) VALUES ((SELECT id FROM roles WHERE name LIKE 'viewer'), 'ORGANISATION_READ');

INSERT INTO role_permissions (role_id, permissions) VALUES ((SELECT id FROM roles WHERE name LIKE 'guest'), 'USER_READ');
INSERT INTO role_permissions (role_id, permissions) VALUES ((SELECT id FROM roles WHERE name LIKE 'guest'), 'ROLE_READ');

INSERT INTO role_permissions (role_id, permissions) VALUES ((SELECT id FROM roles WHERE name LIKE 'observer'), 'USER_READ');
INSERT INTO role_permissions (role_id, permissions) VALUES ((SELECT id FROM roles WHERE name LIKE 'observer'), 'ROLE_READ');

INSERT INTO role_permissions (role_id, permissions) VALUES ((SELECT id FROM roles WHERE name LIKE 'visitor'), 'ORGANISATION_READ');
INSERT INTO role_permissions (role_id, permissions) VALUES ((SELECT id FROM roles WHERE name LIKE 'visitor'), 'ROLE_READ');

INSERT INTO role_permissions (role_id, permissions) VALUES ((SELECT id FROM roles WHERE name LIKE 'admin'), 'ORGANISATION_WRITE');
INSERT INTO role_permissions (role_id, permissions) VALUES ((SELECT id FROM roles WHERE name LIKE 'admin'), 'USER_WRITE');

INSERT INTO role_permissions (role_id, permissions) VALUES ((SELECT id FROM roles WHERE name LIKE 'global admin'), 'ROLE_WRITE');
INSERT INTO role_permissions (role_id, permissions) VALUES ((SELECT id FROM roles WHERE name LIKE 'global admin'), 'USER_WRITE');

INSERT INTO role_permissions (role_id, permissions) VALUES ((SELECT id FROM roles WHERE name LIKE 'custom'), 'USER_READ');
INSERT INTO role_permissions (role_id, permissions) VALUES ((SELECT id FROM roles WHERE name LIKE 'custom'), 'USER_WRITE');

INSERT INTO role_permissions (role_id, permissions) VALUES ((SELECT id FROM roles WHERE name LIKE 'reader'), 'USER_READ');
INSERT INTO role_permissions (role_id, permissions) VALUES ((SELECT id FROM roles WHERE name LIKE 'reader'), 'ORGANISATION_READ');

INSERT INTO role_permissions (role_id, permissions) VALUES ((SELECT id FROM roles WHERE name LIKE 'editor'), 'USER_WRITE');
INSERT INTO role_permissions (role_id, permissions) VALUES ((SELECT id FROM roles WHERE name LIKE 'editor'), 'ORGANISATION_READ');

INSERT INTO role_permissions (role_id, permissions) VALUES ((SELECT id FROM roles WHERE name LIKE 'default'), 'ORGANISATION_WRITE');
INSERT INTO role_permissions (role_id, permissions) VALUES ((SELECT id FROM roles WHERE name LIKE 'default'), 'ORGANISATION_READ');


INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Jan Kowalski'), (SELECT id FROM roles WHERE name LIKE 'default'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Jan Kowalski'), (SELECT id FROM roles WHERE name LIKE 'editor'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Sebastian Kowalski'), (SELECT id FROM roles WHERE name LIKE 'default'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Sebastian Kowalski'), (SELECT id FROM roles WHERE name LIKE 'editor'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Wojciech Kowalski'), (SELECT id FROM roles WHERE name LIKE 'default'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Wojciech Kowalski'), (SELECT id FROM roles WHERE name LIKE 'editor'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Daniel Kowalski'), (SELECT id FROM roles WHERE name LIKE 'default'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Daniel Kowalski'), (SELECT id FROM roles WHERE name LIKE 'editor'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Piotr Kowalski'), (SELECT id FROM roles WHERE name LIKE 'default'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Piotr Kowalski'), (SELECT id FROM roles WHERE name LIKE 'editor'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Eryk Kowalski'), (SELECT id FROM roles WHERE name LIKE 'default'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Eryk Kowalski'), (SELECT id FROM roles WHERE name LIKE 'editor'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Krzysztof Kowalski'), (SELECT id FROM roles WHERE name LIKE 'default'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Krzysztof Kowalski'), (SELECT id FROM roles WHERE name LIKE 'editor'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Cecylia Kowalski'), (SELECT id FROM roles WHERE name LIKE 'default'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Cecylia Kowalski'), (SELECT id FROM roles WHERE name LIKE 'editor'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Barbara Kowalski'), (SELECT id FROM roles WHERE name LIKE 'default'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Barbara Kowalski'), (SELECT id FROM roles WHERE name LIKE 'editor'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Adam Kowalski'), (SELECT id FROM roles WHERE name LIKE 'default'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Adam Kowalski'), (SELECT id FROM roles WHERE name LIKE 'editor'));

INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Jan Nowak'), (SELECT id FROM roles WHERE name LIKE 'reader'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Jan Nowak'), (SELECT id FROM roles WHERE name LIKE 'custom'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Sebastian Nowak'), (SELECT id FROM roles WHERE name LIKE 'reader'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Sebastian Nowak'), (SELECT id FROM roles WHERE name LIKE 'custom'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Wojciech Nowak'), (SELECT id FROM roles WHERE name LIKE 'reader'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Wojciech Nowak'), (SELECT id FROM roles WHERE name LIKE 'custom'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Paweł Nowak'), (SELECT id FROM roles WHERE name LIKE 'reader'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Paweł Nowak'), (SELECT id FROM roles WHERE name LIKE 'custom'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Piotr Nowak'), (SELECT id FROM roles WHERE name LIKE 'reader'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Piotr Nowak'), (SELECT id FROM roles WHERE name LIKE 'custom'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Jacek Nowak'), (SELECT id FROM roles WHERE name LIKE 'reader'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Jacek Nowak'), (SELECT id FROM roles WHERE name LIKE 'custom'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Krzysztof Nowak'), (SELECT id FROM roles WHERE name LIKE 'reader'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Krzysztof Nowak'), (SELECT id FROM roles WHERE name LIKE 'custom'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Michał Nowak'), (SELECT id FROM roles WHERE name LIKE 'reader'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Michał Nowak'), (SELECT id FROM roles WHERE name LIKE 'custom'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Bogdan Nowak'), (SELECT id FROM roles WHERE name LIKE 'reader'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Bogdan Nowak'), (SELECT id FROM roles WHERE name LIKE 'custom'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Adam Nowak'), (SELECT id FROM roles WHERE name LIKE 'reader'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Adam Nowak'), (SELECT id FROM roles WHERE name LIKE 'custom'));

INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Jan Gos'), (SELECT id FROM roles WHERE name LIKE 'admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Jan Gos'), (SELECT id FROM roles WHERE name LIKE 'observer'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Sebastian Gos'), (SELECT id FROM roles WHERE name LIKE 'admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Sebastian Gos'), (SELECT id FROM roles WHERE name LIKE 'observer'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Wojciech Gos'), (SELECT id FROM roles WHERE name LIKE 'admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Wojciech Gos'), (SELECT id FROM roles WHERE name LIKE 'observer'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Paweł Gos'), (SELECT id FROM roles WHERE name LIKE 'admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Paweł Gos'), (SELECT id FROM roles WHERE name LIKE 'observer'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Piotr Gos'), (SELECT id FROM roles WHERE name LIKE 'admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Piotr Gos'), (SELECT id FROM roles WHERE name LIKE 'observer'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Jacek Gos'), (SELECT id FROM roles WHERE name LIKE 'admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Jacek Gos'), (SELECT id FROM roles WHERE name LIKE 'observer'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Krzysztof Gos'), (SELECT id FROM roles WHERE name LIKE 'admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Krzysztof Gos'), (SELECT id FROM roles WHERE name LIKE 'observer'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Michał Gos'), (SELECT id FROM roles WHERE name LIKE 'admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Michał Gos'), (SELECT id FROM roles WHERE name LIKE 'observer'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Bogdan Gos'), (SELECT id FROM roles WHERE name LIKE 'admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Bogdan Gos'), (SELECT id FROM roles WHERE name LIKE 'observer'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Adam Gos'), (SELECT id FROM roles WHERE name LIKE 'admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Adam Gos'), (SELECT id FROM roles WHERE name LIKE 'observer'));

INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Jan Duda'), (SELECT id FROM roles WHERE name LIKE 'admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Jan Duda'), (SELECT id FROM roles WHERE name LIKE 'global admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Sebastian Duda'), (SELECT id FROM roles WHERE name LIKE 'admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Sebastian Duda'), (SELECT id FROM roles WHERE name LIKE 'global admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Wojciech Duda'), (SELECT id FROM roles WHERE name LIKE 'admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Wojciech Duda'), (SELECT id FROM roles WHERE name LIKE 'global admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Paweł Duda'), (SELECT id FROM roles WHERE name LIKE 'admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Paweł Duda'), (SELECT id FROM roles WHERE name LIKE 'global admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Piotr Duda'), (SELECT id FROM roles WHERE name LIKE 'admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Piotr Duda'), (SELECT id FROM roles WHERE name LIKE 'global admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Jacek Duda'), (SELECT id FROM roles WHERE name LIKE 'admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Jacek Duda'), (SELECT id FROM roles WHERE name LIKE 'global admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Krzysztof Duda'), (SELECT id FROM roles WHERE name LIKE 'admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Krzysztof Duda'), (SELECT id FROM roles WHERE name LIKE 'global admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Michał Duda'), (SELECT id FROM roles WHERE name LIKE 'admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Michał Duda'), (SELECT id FROM roles WHERE name LIKE 'global admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Bogdan Duda'), (SELECT id FROM roles WHERE name LIKE 'admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Bogdan Duda'), (SELECT id FROM roles WHERE name LIKE 'global admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Adam Duda'), (SELECT id FROM roles WHERE name LIKE 'admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Adam Duda'), (SELECT id FROM roles WHERE name LIKE 'global admin'));

INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Jan Morawiecki'), (SELECT id FROM roles WHERE name LIKE 'editor'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Jan Morawiecki'), (SELECT id FROM roles WHERE name LIKE 'global admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Sebastian Morawiecki'), (SELECT id FROM roles WHERE name LIKE 'editor'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Sebastian Morawiecki'), (SELECT id FROM roles WHERE name LIKE 'global admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Wojciech Morawiecki'), (SELECT id FROM roles WHERE name LIKE 'editor'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Wojciech Morawiecki'), (SELECT id FROM roles WHERE name LIKE 'global admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Paweł Morawiecki'), (SELECT id FROM roles WHERE name LIKE 'editor'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Paweł Morawiecki'), (SELECT id FROM roles WHERE name LIKE 'global admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Piotr Morawiecki'), (SELECT id FROM roles WHERE name LIKE 'editor'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Piotr Morawiecki'), (SELECT id FROM roles WHERE name LIKE 'global admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Jacek Morawiecki'), (SELECT id FROM roles WHERE name LIKE 'editor'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Jacek Morawiecki'), (SELECT id FROM roles WHERE name LIKE 'global admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Krzysztof Morawiecki'), (SELECT id FROM roles WHERE name LIKE 'editor'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Krzysztof Morawiecki'), (SELECT id FROM roles WHERE name LIKE 'global admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Michał Morawiecki'), (SELECT id FROM roles WHERE name LIKE 'editor'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Michał Morawiecki'), (SELECT id FROM roles WHERE name LIKE 'global admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Bogdan Morawiecki'), (SELECT id FROM roles WHERE name LIKE 'editor'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Bogdan Morawiecki'), (SELECT id FROM roles WHERE name LIKE 'global admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Adam Morawiecki'), (SELECT id FROM roles WHERE name LIKE 'editor'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Adam Morawiecki'), (SELECT id FROM roles WHERE name LIKE 'global admin'));

INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Jan Macierewicz'), (SELECT id FROM roles WHERE name LIKE 'editor'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Jan Macierewicz'), (SELECT id FROM roles WHERE name LIKE 'guest'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Sebastian Macierewicz'), (SELECT id FROM roles WHERE name LIKE 'editor'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Sebastian Macierewicz'), (SELECT id FROM roles WHERE name LIKE 'guest'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Wojciech Macierewicz'), (SELECT id FROM roles WHERE name LIKE 'editor'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Wojciech Macierewicz'), (SELECT id FROM roles WHERE name LIKE 'guest'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Paweł Macierewicz'), (SELECT id FROM roles WHERE name LIKE 'editor'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Paweł Macierewicz'), (SELECT id FROM roles WHERE name LIKE 'guest'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Piotr Macierewicz'), (SELECT id FROM roles WHERE name LIKE 'editor'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Piotr Macierewicz'), (SELECT id FROM roles WHERE name LIKE 'guest'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Jacek Macierewicz'), (SELECT id FROM roles WHERE name LIKE 'editor'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Jacek Macierewicz'), (SELECT id FROM roles WHERE name LIKE 'guest'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Krzysztof Macierewicz'), (SELECT id FROM roles WHERE name LIKE 'editor'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Krzysztof Macierewicz'), (SELECT id FROM roles WHERE name LIKE 'guest'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Michał Macierewicz'), (SELECT id FROM roles WHERE name LIKE 'editor'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Michał Macierewicz'), (SELECT id FROM roles WHERE name LIKE 'guest'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Bogdan Macierewicz'), (SELECT id FROM roles WHERE name LIKE 'editor'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Bogdan Macierewicz'), (SELECT id FROM roles WHERE name LIKE 'guest'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Adam Macierewicz'), (SELECT id FROM roles WHERE name LIKE 'editor'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Adam Macierewicz'), (SELECT id FROM roles WHERE name LIKE 'guest'));

INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Jan Tusk'), (SELECT id FROM roles WHERE name LIKE 'reader'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Jan Tusk'), (SELECT id FROM roles WHERE name LIKE 'guest'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Sebastian Tusk'), (SELECT id FROM roles WHERE name LIKE 'reader'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Sebastian Tusk'), (SELECT id FROM roles WHERE name LIKE 'guest'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Wojciech Tusk'), (SELECT id FROM roles WHERE name LIKE 'reader'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Wojciech Tusk'), (SELECT id FROM roles WHERE name LIKE 'guest'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Paweł Tusk'), (SELECT id FROM roles WHERE name LIKE 'reader'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Paweł Tusk'), (SELECT id FROM roles WHERE name LIKE 'guest'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Piotr Tusk'), (SELECT id FROM roles WHERE name LIKE 'reader'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Piotr Tusk'), (SELECT id FROM roles WHERE name LIKE 'guest'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Jacek Tusk'), (SELECT id FROM roles WHERE name LIKE 'reader'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Jacek Tusk'), (SELECT id FROM roles WHERE name LIKE 'guest'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Krzysztof Tusk'), (SELECT id FROM roles WHERE name LIKE 'reader'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Krzysztof Tusk'), (SELECT id FROM roles WHERE name LIKE 'guest'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Michał Tusk'), (SELECT id FROM roles WHERE name LIKE 'reader'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Michał Tusk'), (SELECT id FROM roles WHERE name LIKE 'guest'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Bogdan Tusk'), (SELECT id FROM roles WHERE name LIKE 'reader'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Bogdan Tusk'), (SELECT id FROM roles WHERE name LIKE 'guest'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Adam Tusk'), (SELECT id FROM roles WHERE name LIKE 'reader'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Adam Tusk'), (SELECT id FROM roles WHERE name LIKE 'guest'));

INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Jan Sikorski'), (SELECT id FROM roles WHERE name LIKE 'reader'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Jan Sikorski'), (SELECT id FROM roles WHERE name LIKE 'custom'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Sebastian Sikorski'), (SELECT id FROM roles WHERE name LIKE 'reader'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Sebastian Sikorski'), (SELECT id FROM roles WHERE name LIKE 'custom'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Wojciech Sikorski'), (SELECT id FROM roles WHERE name LIKE 'reader'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Wojciech Sikorski'), (SELECT id FROM roles WHERE name LIKE 'custom'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Paweł Sikorski'), (SELECT id FROM roles WHERE name LIKE 'reader'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Paweł Sikorski'), (SELECT id FROM roles WHERE name LIKE 'custom'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Piotr Sikorski'), (SELECT id FROM roles WHERE name LIKE 'reader'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Piotr Sikorski'), (SELECT id FROM roles WHERE name LIKE 'custom'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Jacek Sikorski'), (SELECT id FROM roles WHERE name LIKE 'reader'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Jacek Sikorski'), (SELECT id FROM roles WHERE name LIKE 'custom'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Krzysztof Sikorski'), (SELECT id FROM roles WHERE name LIKE 'reader'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Krzysztof Sikorski'), (SELECT id FROM roles WHERE name LIKE 'custom'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Michał Sikorski'), (SELECT id FROM roles WHERE name LIKE 'reader'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Michał Sikorski'), (SELECT id FROM roles WHERE name LIKE 'custom'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Bogdan Sikorski'), (SELECT id FROM roles WHERE name LIKE 'reader'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Bogdan Sikorski'), (SELECT id FROM roles WHERE name LIKE 'custom'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Adam Sikorski'), (SELECT id FROM roles WHERE name LIKE 'reader'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Adam Sikorski'), (SELECT id FROM roles WHERE name LIKE 'custom'));

INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Jan Braun'), (SELECT id FROM roles WHERE name LIKE 'default'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Jan Braun'), (SELECT id FROM roles WHERE name LIKE 'custom'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Sebastian Braun'), (SELECT id FROM roles WHERE name LIKE 'default'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Sebastian Braun'), (SELECT id FROM roles WHERE name LIKE 'custom'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Wojciech Braun'), (SELECT id FROM roles WHERE name LIKE 'default'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Wojciech Braun'), (SELECT id FROM roles WHERE name LIKE 'custom'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Paweł Braun'), (SELECT id FROM roles WHERE name LIKE 'default'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Paweł Braun'), (SELECT id FROM roles WHERE name LIKE 'custom'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Piotr Braun'), (SELECT id FROM roles WHERE name LIKE 'default'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Piotr Braun'), (SELECT id FROM roles WHERE name LIKE 'custom'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Jacek Braun'), (SELECT id FROM roles WHERE name LIKE 'default'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Jacek Braun'), (SELECT id FROM roles WHERE name LIKE 'custom'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Krzysztof Braun'), (SELECT id FROM roles WHERE name LIKE 'default'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Krzysztof Braun'), (SELECT id FROM roles WHERE name LIKE 'custom'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Michał Braun'), (SELECT id FROM roles WHERE name LIKE 'default'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Michał Braun'), (SELECT id FROM roles WHERE name LIKE 'custom'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Bogdan Braun'), (SELECT id FROM roles WHERE name LIKE 'default'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Bogdan Braun'), (SELECT id FROM roles WHERE name LIKE 'custom'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Adam Braun'), (SELECT id FROM roles WHERE name LIKE 'default'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Adam Braun'), (SELECT id FROM roles WHERE name LIKE 'custom'));

INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Jan Mikke'), (SELECT id FROM roles WHERE name LIKE 'default'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Jan Mikke'), (SELECT id FROM roles WHERE name LIKE 'admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Sebastian Mikke'), (SELECT id FROM roles WHERE name LIKE 'default'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Sebastian Mikke'), (SELECT id FROM roles WHERE name LIKE 'admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Wojciech Mikke'), (SELECT id FROM roles WHERE name LIKE 'default'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Wojciech Mikke'), (SELECT id FROM roles WHERE name LIKE 'admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Paweł Mikke'), (SELECT id FROM roles WHERE name LIKE 'default'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Paweł Mikke'), (SELECT id FROM roles WHERE name LIKE 'admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Piotr Mikke'), (SELECT id FROM roles WHERE name LIKE 'default'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Piotr Mikke'), (SELECT id FROM roles WHERE name LIKE 'admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Jacek Mikke'), (SELECT id FROM roles WHERE name LIKE 'default'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Jacek Mikke'), (SELECT id FROM roles WHERE name LIKE 'admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Krzysztof Mikke'), (SELECT id FROM roles WHERE name LIKE 'default'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Krzysztof Mikke'), (SELECT id FROM roles WHERE name LIKE 'admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Michał Mikke'), (SELECT id FROM roles WHERE name LIKE 'admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Michał Mikke'), (SELECT id FROM roles WHERE name LIKE 'custom'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Bogdan Mikke'), (SELECT id FROM roles WHERE name LIKE 'admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Bogdan Mikke'), (SELECT id FROM roles WHERE name LIKE 'custom'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Adam Mikke'), (SELECT id FROM roles WHERE name LIKE 'admin'));
INSERT INTO users_roles (user_id, role_id) VALUES ((SELECT id FROM users WHERE username LIKE 'Adam Mikke'), (SELECT id FROM roles WHERE name LIKE 'custom'));

